// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddBeibaoItem(arg1, arg2, arg3, arg4) {
  return window['go']['main']['app']['AddBeibaoItem'](arg1, arg2, arg3, arg4);
}

export function AddCharacterAttribute(arg1, arg2, arg3, arg4) {
  return window['go']['main']['app']['AddCharacterAttribute'](arg1, arg2, arg3, arg4);
}

export function AddCharacterSkill(arg1, arg2, arg3) {
  return window['go']['main']['app']['AddCharacterSkill'](arg1, arg2, arg3);
}

export function AddDaojuFunction(arg1, arg2, arg3) {
  return window['go']['main']['app']['AddDaojuFunction'](arg1, arg2, arg3);
}

export function AddGuaiwuAttribute(arg1, arg2, arg3, arg4) {
  return window['go']['main']['app']['AddGuaiwuAttribute'](arg1, arg2, arg3, arg4);
}

export function AddGuaiwuSkill(arg1, arg2, arg3) {
  return window['go']['main']['app']['AddGuaiwuSkill'](arg1, arg2, arg3);
}

export function AddPetAttribute(arg1, arg2, arg3, arg4) {
  return window['go']['main']['app']['AddPetAttribute'](arg1, arg2, arg3, arg4);
}

export function AddPetSkill(arg1, arg2, arg3) {
  return window['go']['main']['app']['AddPetSkill'](arg1, arg2, arg3);
}

export function AddShiliAttribute(arg1, arg2, arg3, arg4) {
  return window['go']['main']['app']['AddShiliAttribute'](arg1, arg2, arg3, arg4);
}

export function AddShiliPosition(arg1, arg2, arg3, arg4) {
  return window['go']['main']['app']['AddShiliPosition'](arg1, arg2, arg3, arg4);
}

export function AddShiqingDetail(arg1, arg2) {
  return window['go']['main']['app']['AddShiqingDetail'](arg1, arg2);
}

export function AddWeaponAttribute(arg1, arg2, arg3, arg4) {
  return window['go']['main']['app']['AddWeaponAttribute'](arg1, arg2, arg3, arg4);
}

export function AddWeaponSkill(arg1, arg2, arg3) {
  return window['go']['main']['app']['AddWeaponSkill'](arg1, arg2, arg3);
}

export function CheckDatabaseStatus() {
  return window['go']['main']['app']['CheckDatabaseStatus']();
}

export function CheckReleaseUpdate() {
  return window['go']['main']['app']['CheckReleaseUpdate']();
}

export function ClearDrawHistory() {
  return window['go']['main']['app']['ClearDrawHistory']();
}

export function CreateBeibao(arg1) {
  return window['go']['main']['app']['CreateBeibao'](arg1);
}

export function CreateCharacter(arg1, arg2, arg3, arg4) {
  return window['go']['main']['app']['CreateCharacter'](arg1, arg2, arg3, arg4);
}

export function CreateDaoju(arg1, arg2, arg3) {
  return window['go']['main']['app']['CreateDaoju'](arg1, arg2, arg3);
}

export function CreateGuaiwu(arg1, arg2, arg3, arg4, arg5, arg6, arg7) {
  return window['go']['main']['app']['CreateGuaiwu'](arg1, arg2, arg3, arg4, arg5, arg6, arg7);
}

export function CreatePet(arg1, arg2, arg3) {
  return window['go']['main']['app']['CreatePet'](arg1, arg2, arg3);
}

export function CreatePrize(arg1, arg2, arg3, arg4) {
  return window['go']['main']['app']['CreatePrize'](arg1, arg2, arg3, arg4);
}

export function CreateShili(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['app']['CreateShili'](arg1, arg2, arg3, arg4, arg5);
}

export function CreateShiqing(arg1, arg2, arg3) {
  return window['go']['main']['app']['CreateShiqing'](arg1, arg2, arg3);
}

export function CreateShopping(arg1, arg2, arg3, arg4) {
  return window['go']['main']['app']['CreateShopping'](arg1, arg2, arg3, arg4);
}

export function CreateWeapon(arg1, arg2, arg3) {
  return window['go']['main']['app']['CreateWeapon'](arg1, arg2, arg3);
}

export function DeleteBeibao(arg1) {
  return window['go']['main']['app']['DeleteBeibao'](arg1);
}

export function DeleteBeibaoItem(arg1) {
  return window['go']['main']['app']['DeleteBeibaoItem'](arg1);
}

export function DeleteCharacter(arg1) {
  return window['go']['main']['app']['DeleteCharacter'](arg1);
}

export function DeleteCharacterAttribute(arg1) {
  return window['go']['main']['app']['DeleteCharacterAttribute'](arg1);
}

export function DeleteCharacterSkill(arg1) {
  return window['go']['main']['app']['DeleteCharacterSkill'](arg1);
}

export function DeleteDaoju(arg1) {
  return window['go']['main']['app']['DeleteDaoju'](arg1);
}

export function DeleteDaojuFunction(arg1) {
  return window['go']['main']['app']['DeleteDaojuFunction'](arg1);
}

export function DeleteGuaiwu(arg1) {
  return window['go']['main']['app']['DeleteGuaiwu'](arg1);
}

export function DeleteGuaiwuAttribute(arg1) {
  return window['go']['main']['app']['DeleteGuaiwuAttribute'](arg1);
}

export function DeleteGuaiwuSkill(arg1) {
  return window['go']['main']['app']['DeleteGuaiwuSkill'](arg1);
}

export function DeleteMarkdownFile(arg1) {
  return window['go']['main']['app']['DeleteMarkdownFile'](arg1);
}

export function DeletePet(arg1) {
  return window['go']['main']['app']['DeletePet'](arg1);
}

export function DeletePetAttribute(arg1) {
  return window['go']['main']['app']['DeletePetAttribute'](arg1);
}

export function DeletePetSkill(arg1) {
  return window['go']['main']['app']['DeletePetSkill'](arg1);
}

export function DeletePrize(arg1) {
  return window['go']['main']['app']['DeletePrize'](arg1);
}

export function DeleteShili(arg1) {
  return window['go']['main']['app']['DeleteShili'](arg1);
}

export function DeleteShiliAttribute(arg1) {
  return window['go']['main']['app']['DeleteShiliAttribute'](arg1);
}

export function DeleteShiliPosition(arg1) {
  return window['go']['main']['app']['DeleteShiliPosition'](arg1);
}

export function DeleteShiqing(arg1) {
  return window['go']['main']['app']['DeleteShiqing'](arg1);
}

export function DeleteShiqingDetail(arg1) {
  return window['go']['main']['app']['DeleteShiqingDetail'](arg1);
}

export function DeleteShopping(arg1) {
  return window['go']['main']['app']['DeleteShopping'](arg1);
}

export function DeleteWeapon(arg1) {
  return window['go']['main']['app']['DeleteWeapon'](arg1);
}

export function DeleteWeaponAttribute(arg1) {
  return window['go']['main']['app']['DeleteWeaponAttribute'](arg1);
}

export function DeleteWeaponSkill(arg1) {
  return window['go']['main']['app']['DeleteWeaponSkill'](arg1);
}

export function DrawOnce() {
  return window['go']['main']['app']['DrawOnce']();
}

export function DrawTen() {
  return window['go']['main']['app']['DrawTen']();
}

export function GetAllBeibao() {
  return window['go']['main']['app']['GetAllBeibao']();
}

export function GetAllCharacters() {
  return window['go']['main']['app']['GetAllCharacters']();
}

export function GetAllDaoju() {
  return window['go']['main']['app']['GetAllDaoju']();
}

export function GetAllGuaiwu() {
  return window['go']['main']['app']['GetAllGuaiwu']();
}

export function GetAllPets() {
  return window['go']['main']['app']['GetAllPets']();
}

export function GetAllPrizes() {
  return window['go']['main']['app']['GetAllPrizes']();
}

export function GetAllShili() {
  return window['go']['main']['app']['GetAllShili']();
}

export function GetAllShiqing() {
  return window['go']['main']['app']['GetAllShiqing']();
}

export function GetAllShopping() {
  return window['go']['main']['app']['GetAllShopping']();
}

export function GetAllWeapons() {
  return window['go']['main']['app']['GetAllWeapons']();
}

export function GetBeibaoInfo(arg1) {
  return window['go']['main']['app']['GetBeibaoInfo'](arg1);
}

export function GetCharacterInfo(arg1) {
  return window['go']['main']['app']['GetCharacterInfo'](arg1);
}

export function GetDaojuFunctions(arg1) {
  return window['go']['main']['app']['GetDaojuFunctions'](arg1);
}

export function GetDaojuInfo(arg1) {
  return window['go']['main']['app']['GetDaojuInfo'](arg1);
}

export function GetDatabase() {
  return window['go']['main']['app']['GetDatabase']();
}

export function GetDatabaseInfo() {
  return window['go']['main']['app']['GetDatabaseInfo']();
}

export function GetDrawHistory() {
  return window['go']['main']['app']['GetDrawHistory']();
}

export function GetGuaiwuAttributes(arg1) {
  return window['go']['main']['app']['GetGuaiwuAttributes'](arg1);
}

export function GetGuaiwuInfo(arg1) {
  return window['go']['main']['app']['GetGuaiwuInfo'](arg1);
}

export function GetGuaiwuSkills(arg1) {
  return window['go']['main']['app']['GetGuaiwuSkills'](arg1);
}

export function GetMarkdownFiles() {
  return window['go']['main']['app']['GetMarkdownFiles']();
}

export function GetPetInfo(arg1) {
  return window['go']['main']['app']['GetPetInfo'](arg1);
}

export function GetPrizeInfo(arg1) {
  return window['go']['main']['app']['GetPrizeInfo'](arg1);
}

export function GetShiliAttributes(arg1) {
  return window['go']['main']['app']['GetShiliAttributes'](arg1);
}

export function GetShiliInfo(arg1) {
  return window['go']['main']['app']['GetShiliInfo'](arg1);
}

export function GetShiliPositions(arg1) {
  return window['go']['main']['app']['GetShiliPositions'](arg1);
}

export function GetShiqingDetails(arg1) {
  return window['go']['main']['app']['GetShiqingDetails'](arg1);
}

export function GetShiqingInfo(arg1) {
  return window['go']['main']['app']['GetShiqingInfo'](arg1);
}

export function GetShoppingInfo(arg1) {
  return window['go']['main']['app']['GetShoppingInfo'](arg1);
}

export function GetWeaponInfo(arg1) {
  return window['go']['main']['app']['GetWeaponInfo'](arg1);
}

export function ReadMarkdownFile(arg1) {
  return window['go']['main']['app']['ReadMarkdownFile'](arg1);
}

export function RenameMarkdownFile(arg1, arg2) {
  return window['go']['main']['app']['RenameMarkdownFile'](arg1, arg2);
}

export function SaveMarkdownFile(arg1, arg2) {
  return window['go']['main']['app']['SaveMarkdownFile'](arg1, arg2);
}

export function StartAutoUpdate() {
  return window['go']['main']['app']['StartAutoUpdate']();
}

export function UpdateBeibao(arg1, arg2) {
  return window['go']['main']['app']['UpdateBeibao'](arg1, arg2);
}

export function UpdateBeibaoItem(arg1, arg2, arg3, arg4) {
  return window['go']['main']['app']['UpdateBeibaoItem'](arg1, arg2, arg3, arg4);
}

export function UpdateCharacterAttribute(arg1, arg2, arg3, arg4) {
  return window['go']['main']['app']['UpdateCharacterAttribute'](arg1, arg2, arg3, arg4);
}

export function UpdateCharacterBasicInfo(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['app']['UpdateCharacterBasicInfo'](arg1, arg2, arg3, arg4, arg5);
}

export function UpdateCharacterSkill(arg1, arg2, arg3) {
  return window['go']['main']['app']['UpdateCharacterSkill'](arg1, arg2, arg3);
}

export function UpdateDaojuBasicInfo(arg1, arg2, arg3) {
  return window['go']['main']['app']['UpdateDaojuBasicInfo'](arg1, arg2, arg3);
}

export function UpdateDaojuFunction(arg1, arg2, arg3) {
  return window['go']['main']['app']['UpdateDaojuFunction'](arg1, arg2, arg3);
}

export function UpdateGuaiwuAttribute(arg1, arg2, arg3, arg4) {
  return window['go']['main']['app']['UpdateGuaiwuAttribute'](arg1, arg2, arg3, arg4);
}

export function UpdateGuaiwuBasicInfo(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['app']['UpdateGuaiwuBasicInfo'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function UpdateGuaiwuSkill(arg1, arg2, arg3) {
  return window['go']['main']['app']['UpdateGuaiwuSkill'](arg1, arg2, arg3);
}

export function UpdatePetAttribute(arg1, arg2, arg3, arg4) {
  return window['go']['main']['app']['UpdatePetAttribute'](arg1, arg2, arg3, arg4);
}

export function UpdatePetBasicInfo(arg1, arg2, arg3) {
  return window['go']['main']['app']['UpdatePetBasicInfo'](arg1, arg2, arg3);
}

export function UpdatePetSkill(arg1, arg2, arg3) {
  return window['go']['main']['app']['UpdatePetSkill'](arg1, arg2, arg3);
}

export function UpdatePrize(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['app']['UpdatePrize'](arg1, arg2, arg3, arg4, arg5);
}

export function UpdateShiliAttribute(arg1, arg2, arg3, arg4) {
  return window['go']['main']['app']['UpdateShiliAttribute'](arg1, arg2, arg3, arg4);
}

export function UpdateShiliBasicInfo(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['app']['UpdateShiliBasicInfo'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function UpdateShiliPosition(arg1, arg2, arg3, arg4) {
  return window['go']['main']['app']['UpdateShiliPosition'](arg1, arg2, arg3, arg4);
}

export function UpdateShiqingBasicInfo(arg1, arg2, arg3) {
  return window['go']['main']['app']['UpdateShiqingBasicInfo'](arg1, arg2, arg3);
}

export function UpdateShiqingDetail(arg1, arg2) {
  return window['go']['main']['app']['UpdateShiqingDetail'](arg1, arg2);
}

export function UpdateShopping(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['app']['UpdateShopping'](arg1, arg2, arg3, arg4, arg5);
}

export function UpdateWeaponAttribute(arg1, arg2, arg3, arg4) {
  return window['go']['main']['app']['UpdateWeaponAttribute'](arg1, arg2, arg3, arg4);
}

export function UpdateWeaponBasicInfo(arg1, arg2, arg3, arg4) {
  return window['go']['main']['app']['UpdateWeaponBasicInfo'](arg1, arg2, arg3, arg4);
}

export function UpdateWeaponSkill(arg1, arg2, arg3) {
  return window['go']['main']['app']['UpdateWeaponSkill'](arg1, arg2, arg3);
}
