// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddCharacterAttribute(arg1, arg2, arg3, arg4) {
  return window['go']['main']['app']['AddCharacterAttribute'](arg1, arg2, arg3, arg4);
}

export function AddCharacterSkill(arg1, arg2, arg3) {
  return window['go']['main']['app']['AddCharacterSkill'](arg1, arg2, arg3);
}

export function CheckDatabaseStatus() {
  return window['go']['main']['app']['CheckDatabaseStatus']();
}

export function CreateCharacter(arg1, arg2, arg3, arg4) {
  return window['go']['main']['app']['CreateCharacter'](arg1, arg2, arg3, arg4);
}

export function DeleteCharacter(arg1) {
  return window['go']['main']['app']['DeleteCharacter'](arg1);
}

export function DeleteCharacterAttribute(arg1) {
  return window['go']['main']['app']['DeleteCharacterAttribute'](arg1);
}

export function DeleteCharacterSkill(arg1) {
  return window['go']['main']['app']['DeleteCharacterSkill'](arg1);
}

export function GetAllCharacters() {
  return window['go']['main']['app']['GetAllCharacters']();
}

export function GetCharacterInfo(arg1) {
  return window['go']['main']['app']['GetCharacterInfo'](arg1);
}

export function GetDatabase() {
  return window['go']['main']['app']['GetDatabase']();
}

export function GetDatabaseInfo() {
  return window['go']['main']['app']['GetDatabaseInfo']();
}

export function UpdateCharacterAttribute(arg1, arg2, arg3, arg4) {
  return window['go']['main']['app']['UpdateCharacterAttribute'](arg1, arg2, arg3, arg4);
}

export function UpdateCharacterBasicInfo(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['app']['UpdateCharacterBasicInfo'](arg1, arg2, arg3, arg4, arg5);
}

export function UpdateCharacterSkill(arg1, arg2, arg3) {
  return window['go']['main']['app']['UpdateCharacterSkill'](arg1, arg2, arg3);
}
