// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {database} from '../models';

export function AddCharacterAttribute(arg1:number,arg2:string,arg3:string,arg4:number):Promise<void>;

export function AddCharacterSkill(arg1:number,arg2:string,arg3:string):Promise<void>;

export function CheckDatabaseStatus():Promise<boolean|string>;

export function CreateCharacter(arg1:string,arg2:string,arg3:number,arg4:number):Promise<number>;

export function DeleteCharacter(arg1:number):Promise<void>;

export function DeleteCharacterAttribute(arg1:number):Promise<void>;

export function DeleteCharacterSkill(arg1:number):Promise<void>;

export function GetAllCharacters():Promise<Array<Record<string, any>>>;

export function GetCharacterInfo(arg1:number):Promise<Record<string, any>>;

export function GetDatabase():Promise<database.Database>;

export function GetDatabaseInfo():Promise<Record<string, any>>;

export function UpdateCharacterBasicInfo(arg1:number,arg2:string,arg3:string,arg4:number,arg5:number):Promise<void>;
