// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {database} from '../models';

export function AddBeibaoItem(arg1:number,arg2:string,arg3:number,arg4:string):Promise<void>;

export function AddCharacterAttribute(arg1:number,arg2:string,arg3:string,arg4:number):Promise<void>;

export function AddCharacterSkill(arg1:number,arg2:string,arg3:string):Promise<void>;

export function AddDaojuFunction(arg1:number,arg2:string,arg3:string):Promise<void>;

export function AddGuaiwuAttribute(arg1:number,arg2:string,arg3:string,arg4:number):Promise<void>;

export function AddGuaiwuSkill(arg1:number,arg2:string,arg3:string):Promise<void>;

export function AddPetAttribute(arg1:number,arg2:string,arg3:string,arg4:number):Promise<void>;

export function AddPetSkill(arg1:number,arg2:string,arg3:string):Promise<void>;

export function AddShiliAttribute(arg1:number,arg2:string,arg3:string,arg4:number):Promise<void>;

export function AddShiliPosition(arg1:number,arg2:string,arg3:string,arg4:string):Promise<void>;

export function AddShiqingDetail(arg1:number,arg2:string):Promise<void>;

export function AddWeaponAttribute(arg1:number,arg2:string,arg3:string,arg4:number):Promise<void>;

export function AddWeaponSkill(arg1:number,arg2:string,arg3:string):Promise<void>;

export function CheckDatabaseStatus():Promise<boolean|string>;

export function CreateBeibao(arg1:string):Promise<number>;

export function CreateCharacter(arg1:string,arg2:string,arg3:number,arg4:number):Promise<number>;

export function CreateDaoju(arg1:string,arg2:string,arg3:number):Promise<number>;

export function CreateGuaiwu(arg1:string,arg2:string,arg3:number,arg4:number,arg5:number,arg6:number,arg7:string):Promise<number>;

export function CreatePet(arg1:string,arg2:string,arg3:number):Promise<number>;

export function CreateShili(arg1:string,arg2:string,arg3:number,arg4:number,arg5:number):Promise<number>;

export function CreateShiqing(arg1:string,arg2:string,arg3:string):Promise<number>;

export function CreateWeapon(arg1:string,arg2:string,arg3:number):Promise<number>;

export function DeleteBeibao(arg1:number):Promise<void>;

export function DeleteBeibaoItem(arg1:number):Promise<void>;

export function DeleteCharacter(arg1:number):Promise<void>;

export function DeleteCharacterAttribute(arg1:number):Promise<void>;

export function DeleteCharacterSkill(arg1:number):Promise<void>;

export function DeleteDaoju(arg1:number):Promise<void>;

export function DeleteDaojuFunction(arg1:number):Promise<void>;

export function DeleteGuaiwu(arg1:number):Promise<void>;

export function DeleteGuaiwuAttribute(arg1:number):Promise<void>;

export function DeleteGuaiwuSkill(arg1:number):Promise<void>;

export function DeleteMarkdownFile(arg1:string):Promise<void>;

export function DeletePet(arg1:number):Promise<void>;

export function DeletePetAttribute(arg1:number):Promise<void>;

export function DeletePetSkill(arg1:number):Promise<void>;

export function DeleteShili(arg1:number):Promise<void>;

export function DeleteShiliAttribute(arg1:number):Promise<void>;

export function DeleteShiliPosition(arg1:number):Promise<void>;

export function DeleteShiqing(arg1:number):Promise<void>;

export function DeleteShiqingDetail(arg1:number):Promise<void>;

export function DeleteWeapon(arg1:number):Promise<void>;

export function DeleteWeaponAttribute(arg1:number):Promise<void>;

export function DeleteWeaponSkill(arg1:number):Promise<void>;

export function GetAllBeibao():Promise<Array<Record<string, any>>>;

export function GetAllCharacters():Promise<Array<Record<string, any>>>;

export function GetAllDaoju():Promise<Array<Record<string, any>>>;

export function GetAllGuaiwu():Promise<Array<Record<string, any>>>;

export function GetAllPets():Promise<Array<Record<string, any>>>;

export function GetAllShili():Promise<Array<Record<string, any>>>;

export function GetAllShiqing():Promise<Array<Record<string, any>>>;

export function GetAllWeapons():Promise<Array<Record<string, any>>>;

export function GetBeibaoInfo(arg1:number):Promise<Record<string, any>>;

export function GetCharacterInfo(arg1:number):Promise<Record<string, any>>;

export function GetDaojuFunctions(arg1:number):Promise<Array<Record<string, any>>>;

export function GetDaojuInfo(arg1:number):Promise<Record<string, any>>;

export function GetDatabase():Promise<database.Database>;

export function GetDatabaseInfo():Promise<Record<string, any>>;

export function GetGuaiwuAttributes(arg1:number):Promise<Array<Record<string, any>>>;

export function GetGuaiwuInfo(arg1:number):Promise<Record<string, any>>;

export function GetGuaiwuSkills(arg1:number):Promise<Array<Record<string, any>>>;

export function GetMarkdownFiles():Promise<Array<Record<string, any>>>;

export function GetPetInfo(arg1:number):Promise<Record<string, any>>;

export function GetShiliAttributes(arg1:number):Promise<Array<Record<string, any>>>;

export function GetShiliInfo(arg1:number):Promise<Record<string, any>>;

export function GetShiliPositions(arg1:number):Promise<Array<Record<string, any>>>;

export function GetShiqingDetails(arg1:number):Promise<Array<Record<string, any>>>;

export function GetShiqingInfo(arg1:number):Promise<Record<string, any>>;

export function GetWeaponInfo(arg1:number):Promise<Record<string, any>>;

export function ReadMarkdownFile(arg1:string):Promise<string>;

export function RenameMarkdownFile(arg1:string,arg2:string):Promise<void>;

export function SaveMarkdownFile(arg1:string,arg2:string):Promise<void>;

export function UpdateBeibao(arg1:number,arg2:string):Promise<void>;

export function UpdateBeibaoItem(arg1:number,arg2:string,arg3:number,arg4:string):Promise<void>;

export function UpdateCharacterAttribute(arg1:number,arg2:string,arg3:string,arg4:number):Promise<void>;

export function UpdateCharacterBasicInfo(arg1:number,arg2:string,arg3:string,arg4:number,arg5:number):Promise<void>;

export function UpdateCharacterSkill(arg1:number,arg2:string,arg3:string):Promise<void>;

export function UpdateDaojuBasicInfo(arg1:number,arg2:string,arg3:number):Promise<void>;

export function UpdateDaojuFunction(arg1:number,arg2:string,arg3:string):Promise<void>;

export function UpdateGuaiwuAttribute(arg1:number,arg2:string,arg3:string,arg4:number):Promise<void>;

export function UpdateGuaiwuBasicInfo(arg1:number,arg2:number,arg3:number,arg4:number,arg5:number,arg6:string):Promise<void>;

export function UpdateGuaiwuSkill(arg1:number,arg2:string,arg3:string):Promise<void>;

export function UpdatePetAttribute(arg1:number,arg2:string,arg3:string,arg4:number):Promise<void>;

export function UpdatePetBasicInfo(arg1:number,arg2:string,arg3:number):Promise<void>;

export function UpdatePetSkill(arg1:number,arg2:string,arg3:string):Promise<void>;

export function UpdateShiliAttribute(arg1:number,arg2:string,arg3:string,arg4:number):Promise<void>;

export function UpdateShiliBasicInfo(arg1:number,arg2:number,arg3:string,arg4:number,arg5:number,arg6:number):Promise<void>;

export function UpdateShiliPosition(arg1:number,arg2:string,arg3:string,arg4:string):Promise<void>;

export function UpdateShiqingBasicInfo(arg1:number,arg2:string,arg3:string):Promise<void>;

export function UpdateShiqingDetail(arg1:number,arg2:string):Promise<void>;

export function UpdateWeaponAttribute(arg1:number,arg2:string,arg3:string,arg4:number):Promise<void>;

export function UpdateWeaponBasicInfo(arg1:number,arg2:string,arg3:string,arg4:number):Promise<void>;

export function UpdateWeaponSkill(arg1:number,arg2:string,arg3:string):Promise<void>;
